@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.surfacerule;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;