@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.event;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;