@FieldsAreNonnullByDefault
@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
@TypeUseAreNonnullByDefault
package tamaized.voidscape.coremod.transformers.entity.render;

import com.mojang.logging.annotations.FieldsAreNonnullByDefault;
import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;
import tamaized.pkginfoutil.TypeUseAreNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;