@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.entity.abilities.mage;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;