@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.client.event;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;