import net.neoforged.moddevgradle.internal.RunGameTask
import com.github.jengelman.gradle.plugins.shadow.relocation.SimpleRelocator

buildscript {
	repositories {
		maven {
			name 'Beanification'
			url 'https://maven.tamaized.com/releases/'
		}
	}
	dependencies {
		classpath "tamaized:beanification:${beanification_gradle_plugin_version}:gradle"
	}
}

plugins {
	id 'java-library'
	id 'eclipse'
	id 'idea'
	id 'maven-publish'
	// Version List: https://projects.neoforged.net/neoforged/ModDevGradle
	id 'net.neoforged.moddev' version "${mdg_version}"
	id "com.dorongold.task-tree" version "4.0.0"
	id 'com.gradleup.shadow' version "${shadowjar_version}"
}

apply plugin: 'tamaized.beanification'

repositories {
	gradlePluginPortal()
}

dependencies { // Forces intellij to grab sources for the gradle build script
	compileOnly "com.gradleup.shadow:shadow-gradle-plugin:${shadowjar_version}"
	compileOnly "net.neoforged.moddev:net.neoforged.moddev.gradle.plugin:${mdg_version}"
}

wrapper {
	gradleVersion = '9.1.0'
	distributionType = Wrapper.DistributionType.ALL
}

configurations {
	shade
}

shadowJar {
	mustRunAfter jar
	archiveClassifier.set('')
	configurations = [project.configurations.shade]
	relocate(new SimpleRelocator('tamaized', 'tamaized.beatdownstick')) {
		exclude 'tamaized.beatdownstick.**'
	}
}

def secrets = new Properties()
def secretsFile = file('secrets.properties')
if (secretsFile.exists()) {
	secretsFile.withInputStream {
		stream -> secrets.load(stream)
	}

	fileTree("secrets").matching {
		include "**/*.properties"
	}.each {
		File file ->
			file.withInputStream {
				stream -> secrets.load(stream)
			}
	}
}

idea {
	module {
		downloadJavadoc = true
		downloadSources = true
	}
}

version = "${project.minecraft_version}-${project.mod_major_version}." + (hasProperty("CIVersion") ? CIVersion : mod_version)
group = "tamaized.${project.mod_id}"

base {
	archivesName = "Voidscape"
}

subprojects {
	version = project(":").version
}

java {
	toolchain {
		languageVersion.set(JavaLanguageVersion.of(25))
	}
}

tasks.withType(JavaCompile).configureEach {
	options.compilerArgs << "-Xlint:all,-classfile,-processing,-deprecation,-this-escape" << "-Werror"
	options.encoding = 'UTF-8'
}

sourceSets {
	data {
		compileClasspath += main.compileClasspath + main.output

		java {
			srcDirs = ['src/main/java', 'src/data/java']
		}
		resources {
			srcDirs = ['src/main/resources']
		}
	}
	dataForPublishing {
		compileClasspath += data.compileClasspath

		java {
			srcDirs = ['src/data/java']
		}
	}
}

configurations {
	dataImplementation.extendsFrom implementation
}

neoForge {
	evaluationDependsOnChildren()

	def mod_id = project.mod_id
	version = project.neoforge_version

	validateAccessTransformers = true

	addModdingDependenciesTo sourceSets.data

	mods {
		"${mod_id}" {
			it.sourceSet this.sourceSets.main
		}

		"${mod_id}-data" {
			it.sourceSet this.sourceSets.main
			it.sourceSet this.sourceSets.data
		}

		'asm' {
			it.sourceSet project(":asm").sourceSets.main
		}
	}

	def mainMod = mods."${project.mod_id}"
	def dataMod = mods."${project.mod_id}-data"
	def asmMod = mods."asm"

	unitTest {
		enable()
		testedMod = mainMod
		loadedMods = [mainMod]
	}

	runs {
		configureEach {
			gameDirectory = project.file('run')
			systemProperty 'forge.logging.console.level', 'debug'
			logLevel = org.slf4j.event.Level.DEBUG
			loadedMods = [mainMod, asmMod]
		}

		client {
			client()
			systemProperty 'forge.enabledGameTestNamespaces', mod_id
			programArguments.addAll(
				'--username', secrets.getProperty("username") ?: 'Dev',
				'--accessToken', '0',
				secrets.getProperty("uuid") ? '--uuid' : '', secrets.getProperty("uuid") ?: ''
			)
		}

		server {
			server()
			systemProperty 'forge.enabledGameTestNamespaces', mod_id
			programArgument '--nogui'
		}

		data {
			clientData()
			gameDirectory = project.file('run-data')
			programArguments.addAll(
				'--mod', mod_id,
				'--all',
				'--output', file('src/generated/resources/').getAbsolutePath(),
				'--existing', file('src/main/resources/').getAbsolutePath()
			)
			sourceSet = this.sourceSets.data
			loadedMods = [dataMod, asmMod]
		}
	}
}

afterEvaluate {
	tasks.withType(RunGameTask).configureEach {
		classpathProvider.setFrom(classpathProvider.files.stream().filter(f -> !f.toString().contains('/asm/build/')).toList())
	}
}

def gprUser = hasProperty("GPRUser") ? GPRUser : secrets.getProperty("gpr.user")
def gprKey = hasProperty("GPRKey") ? GPRKey : secrets.getProperty("gpr.key")

repositories {
	maven {
		name 'Jared\'s Maven' // JEI
		url 'https://maven.blamejared.com/'
	}
	maven {
		name 'Tama\'s Maven'
		url 'https://maven.tamaized.com/releases/'
	}
	maven {
		name 'Modrinth\'s Maven' // EnderIO
		url "https://api.modrinth.com/maven"
	}
	// https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#authenticating-with-a-personal-access-token
	maven {
		url = uri("https://maven.pkg.github.com/The-Aether-Team/The-Aether")
		credentials {
			username = gprUser
			password = gprKey
		}
	}
	maven { url 'https://maven.wispforest.io' } // Aether - owolib
	maven { url = "https://maven.su5ed.dev/releases" } // Aether - owolib - Sinytra
}

dependencies {
	jarJar implementation(project(":asm"))

	runtimeOnly "mezz.jei:jei-${project.minecraft_version}-neoforge:${project.jei_version}"
//    runtimeOnly fg.deobf("maven.modrinth:enderio:6.0.18-alpha")

	/*def aether = "com.aetherteam.aether:aether:1.21.1-1.5.8-neoforge"
    runtimeOnly aether
	dataImplementation aether
	def aetherLib = "io.wispforest:owo-lib-neoforge:0.12.15.1-beta.3+1.21"
	runtimeOnly aetherLib
	dataRuntimeOnly aetherLib*/

	def regUtil = "tamaized:regutil:${project.regutil_version}"
	implementation regUtil
	shade regUtil

	def beanification = "tamaized:beanification:"
	testImplementation "${beanification}:tests"
	testCompileOnly "${beanification}:test-sources"

	afterEvaluate {
		def pkg = rootProject.configurations.compileClasspath
			.resolvedConfiguration.resolvedArtifacts
			.find { it.name == 'pkginfoutil' }?.moduleVersion?.id
		if (pkg != null) {
			project(':asm').dependencies {
				compileOnly pkg.toString()
			}
		}
	}

	testImplementation "net.neoforged:testframework:${project.neoforge_version}"
	testImplementation "org.junit.jupiter:junit-jupiter:6.0.1"
	testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:6.0.1"
	testRuntimeOnly "org.junit.platform:junit-platform-launcher:6.0.1"
	testImplementation "org.mockito:mockito-junit-jupiter:5.21.0"
}

configurations.testImplementation {
	exclude module: 'asm'
}

test {
	useJUnitPlatform()
	testLogging {
		events "failed"

		showExceptions true
		exceptionFormat "full"
		showCauses true
		showStackTraces true

		showStandardStreams = false
	}
}

sourceSets.main.resources {
	srcDir 'src/generated/resources'
	exclude '.cache'
}

processResources {
	def ver = project.version
	filesMatching("META-INF/neoforge.mods.toml") {
		expand([
			'file': [
				'jarVersion': ver
			]
		])
	}
}

jar {
	manifest {
		attributes([
			"Specification-Title"     : "Voidscape",
			"Specification-Vendor"    : "Tamaized",
			"Specification-Version"   : "${version}",
			"Implementation-Title"    : project.name,
			"Implementation-Version"  : "${version}",
			"Implementation-Vendor"   : "Tamaized",
			"Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
		])
	}
}

def mavenUser = hasProperty("CIMUser") ? CIMUser : secrets.getProperty("maven_username")
def mavenToken = hasProperty("CIMToken") ? CIMToken : secrets.getProperty("maven_password")

publishing {
	publications {
		create('mavenJava', MavenPublication) {
			afterEvaluate {
				artifact this.project.jar
				artifact this.project.sourceJar
				artifact this.project.dataJar
				artifact this.project.dataSourceJar
			}
			groupId 'tamaized'
			artifactId this.project.mod_id

			def depsProvider = this.project.provider {
				[
					regutil_version: this.project.regutil_version
				]
			}

			pom.withXml {
				def dependenciesNode = asNode().appendNode('dependencies')

				def addDep = { String group, String name, String version ->
					def depNode = dependenciesNode.appendNode('dependency')
					depNode.appendNode('groupId', group)
					depNode.appendNode('artifactId', name)
					depNode.appendNode('version', version)
					depNode.appendNode('scope', 'compile')
				}

				def deps = depsProvider.get()

				addDep('tamaized', 'regutil', deps.regutil_version)
			}
		}
	}
	repositories {
		maven {
			url "https://maven.tamaized.com/releases"
			credentials {
				username mavenUser
				password mavenToken
			}
		}
	}
}

tasks.register('sourceJar', Jar) {
	dependsOn 'classes'
	from sourceSets.main.allSource
	archiveClassifier = 'sources'
}

tasks.register('dataJar', Jar) {
	dependsOn 'classes'
	from sourceSets.dataForPublishing.output
	archiveClassifier = 'data'
}

tasks.register('dataSourceJar', Jar) {
	dependsOn 'classes'
	from sourceSets.dataForPublishing.allSource
	archiveClassifier = 'data-sources'
}

build.dependsOn shadowJar
