org.gradle.jvmargs=-Xmx4000M
org.gradle.daemon=false
org.gradle.configuration-cache=true

shadowjar_version=9.4.1

# NeoForge Versions: https://projects.neoforged.net/neoforged/neoforge
base_minecraft_version=26.1
minecraft_version=26.1.2
neoforge_version=26.1.2.61-beta
mdg_version=2.0.141

beanification_gradle_plugin_version=1.9.129

regutil_version=2.1.78

jei_version=19.8.2.99

mod_id=voidscape
mod_major_version=1.10
mod_version=0
