org.gradle.jvmargs=-Xmx4000M
org.gradle.daemon=false
org.gradle.configuration-cache=true

shadowjar_version=9.4.1

# NeoForge Versions: https://projects.neoforged.net/neoforged/neoforge
minecraft_version=26.1.2
neoforge_version=26.1.2.99
mdg_version=2.0.141

beanification_gradle_plugin_version=1.9.129

regutil_version=2.1.79

jei_version=29.29.0.85

mod_id=voidscape
mod_major_version=1.10
mod_version=0
