org.gradle.jvmargs=-Xmx4000M
org.gradle.daemon=false
org.gradle.configuration-cache=true

# Versions: https://parchmentmc.org/docs/getting-started
neoForge.parchment.minecraftVersion=1.21.1
neoForge.parchment.mappingsVersion=2024.11.17

# NeoForge: https://projects.neoforged.net/neoforged/neoforge
base_minecraft_version=1.21
minecraft_version=1.21.1
neoforge_version=21.1.72
mdg_version=2.0.76

beanification_version=1.4.87
regutil_version=1.10.54
jei_version=19.8.2.99

mod_id=voidscape
mod_major_version=1.8
mod_version=0
