@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.entity.ai.nullservant;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;