@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.asm;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;