@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.turmoil.skills;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;