@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.client.particle;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;