@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.turmoil.caps;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;