@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.network;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;