@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.dimension;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;