@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.entity.abilities;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;