@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.util;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;