@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.structure;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;