@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.turmoil.abilities;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;