@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.client.entity.render;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;