@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.client.entity.render;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;