@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.party;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;