@FieldsAreNonnullByDefault
@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
@TypeUseAreNonnullByDefault
package tamaized.voidscape.client.entity.render.state;

import com.mojang.logging.annotations.FieldsAreNonnullByDefault;
import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;
import tamaized.pkginfoutil.TypeUseAreNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;