@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.config;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;