@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.block.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;