@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.advancement;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;