@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.registry.fluid;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;