@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.features.placements;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;