@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.registry.feature;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;