@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.effect;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;