@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.world.structures;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;