@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.entity.abilities;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;