@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.config.common;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;