@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.config.client;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;