@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.network.common;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;