@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.registry.item;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;