@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.registry.block;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;