@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.network.server;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;