@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.network.server;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;