@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.registry.blockentity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;