@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.features.config;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;