@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.voidscape.client.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;